import { Platform, StyleSheet } from 'react-native';
import { RoomChatDensity, RoomChatVisualTokens } from './roomChatVisualTokens';

export const createRoomChatStyles = (tokens: RoomChatVisualTokens, density: RoomChatDensity) => {
  const subtleShadow = Platform.select({
    ios: {
      shadowColor: tokens.shadow,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.14,
      shadowRadius: 10,
    },
    android: {
      elevation: 3,
    },
  });

  const cardShadow = Platform.select({
    ios: {
      shadowColor: tokens.shadow,
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.12,
      shadowRadius: 22,
    },
    android: {
      elevation: 8,
    },
  });

  return StyleSheet.create({
    container: { flex: 1 },
    center: { flex: 1, justifyContent: 'center', alignItems: 'center' },

    headerBackground: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'transparent',
    },
    headerWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      paddingBottom: 10,
      minHeight: 64,
      borderBottomWidth: 1,
      borderBottomColor: tokens.headerBorder,
      backgroundColor: 'transparent',
      overflow: 'visible',
    },
    headerTitleText: {
      flex: 1,
      fontSize: 17,
      color: tokens.headerTitle,
      fontFamily: tokens.fontFamily,
      fontWeight: tokens.fontWeightSemibold,
      textAlign: 'center',
    },
    headerBackButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      marginLeft: 0,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: tokens.headerActionButtonOpaque,
      borderWidth: 1,
      borderColor: tokens.headerBorder,
    },
    headerRightRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginRight: 0,
      gap: 10,
    },
    headerBalanceWrap: {
      marginRight: 2,
    },
    headerActionButton: {
      width: 44,
      height: 44,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: tokens.headerActionButtonOpaque,
      borderWidth: 1,
      borderColor: tokens.headerBorder,
    },

    readerCardShell: {
      borderRadius: density.radiusXl,
      marginHorizontal: 12,
      marginTop: 4,
      marginBottom: 8,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: tokens.readerCardBorder,
      backgroundColor: tokens.readerCardOpaque,
      ...cardShadow,
    },
    readerCardOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: tokens.readerCard,
    },
    readingHeader: {
      flexDirection: 'column',
      alignItems: 'stretch',
      paddingHorizontal: density.spacingLg + 2,
      paddingTop: density.spacingLg + 2,
      paddingBottom: density.spacingSm,
    },
    readingHeaderTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    readingHeaderTextWrap: {
      flex: 1,
      marginRight: 8,
      minWidth: 0,
    },
    bookTitle: {
      fontSize: 20,
      lineHeight: 24,
      letterSpacing: -0.25,
      fontFamily: tokens.fontFamily,
      fontWeight: tokens.fontWeightSemibold,
      color: tokens.readerPrimaryText,
    },
    joinCallButton: {
      paddingHorizontal: 22,
      paddingVertical: 12,
      borderRadius: density.radiusPill,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: tokens.accent,
      borderWidth: 1,
      borderColor: 'rgba(0,0,0,0.04)',
      ...subtleShadow,
    },
    joinCallButtonFullWidth: {
      width: '100%',
    },
    joinCallButtonText: {
      color: tokens.accentTextOnPrimary,
      fontFamily: tokens.fontFamily,
      fontWeight: tokens.fontWeightBold,
      fontSize: 14,
      lineHeight: 17,
      letterSpacing: 0.2,
    },
    toggleReaderButton: {
      width: 38,
      height: 38,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: tokens.readerDivider,
      backgroundColor: tokens.readerNavCard,
      marginLeft: 6,
    },

    navCard: {
      borderRadius: density.radiusLg,
      marginHorizontal: density.spacingLg,
      marginBottom: density.spacingLg,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: tokens.readerDivider,
      backgroundColor: tokens.readerNavCard,
    },
    navRow: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 56,
    },
    navRowDivider: {
      borderTopWidth: 1,
      borderTopColor: tokens.readerDivider,
    },
    navEdgeButton: {
      width: 50,
      alignItems: 'center',
      justifyContent: 'center',
    },
    navLabelCell: {
      width: 86,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 56,
      backgroundColor: tokens.readerNavLabel,
    },
    navLabelText: {
      fontSize: 11,
      lineHeight: 13,
      color: tokens.readerSecondaryText,
      fontFamily: tokens.fontFamily,
      fontWeight: tokens.fontWeightBold,
      textTransform: 'uppercase',
      letterSpacing: 1.2,
    },
    navScroll: {
      flex: 1,
    },
    navItem: {
      minWidth: 54,
      height: 56,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 14,
      borderRadius: 12,
      marginHorizontal: 4,
      marginVertical: 5,
    },
    navItemActive: {
      backgroundColor: 'rgba(255,122,26,0.14)',
    },
    navItemText: {
      fontSize: 17,
      lineHeight: 20,
      fontFamily: tokens.fontFamily,
      fontWeight: tokens.fontWeightSemibold,
      color: tokens.readerSecondaryText,
    },
    verseNavItem: {
      width: 44,
      height: 38,
      borderRadius: 11,
      justifyContent: 'center',
      alignItems: 'center',
      marginHorizontal: 3,
      borderWidth: 1,
      borderColor: 'transparent',
    },
    verseNavItemText: {
      fontSize: 15,
      lineHeight: 17,
      fontFamily: tokens.fontFamily,
      fontWeight: tokens.fontWeightSemibold,
      color: tokens.readerSecondaryText,
    },

    verseContentWrap: {
      flex: 1,
    },
    verseScroll: {
      flex: 1,
    },
    verseScrollContent: {
      paddingHorizontal: density.spacingLg,
      paddingBottom: density.spacingLg,
    },
    sanskritText: {
      textAlign: 'center',
      marginBottom: 16,
      color: tokens.readerPrimaryText,
      fontFamily: tokens.fontFamily,
      fontStyle: 'italic',
    },
    translationText: {
      color: tokens.readerSecondaryText,
      marginBottom: 14,
      fontFamily: tokens.fontFamily,
    },
    purportContainer: {
      marginTop: 16,
      paddingTop: 16,
      borderTopWidth: 1,
      borderTopColor: tokens.readerDivider,
    },
    purportHeader: {
      marginBottom: 10,
      color: tokens.accent,
      fontSize: 13,
      lineHeight: 16,
      fontFamily: tokens.fontFamily,
      fontWeight: tokens.fontWeightBold,
      textTransform: 'uppercase',
      letterSpacing: 1.2,
    },
    purportText: {
      color: tokens.readerSecondaryText,
      fontFamily: tokens.fontFamily,
    },
    readingControls: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: density.spacingLg,
      paddingVertical: density.spacingMd,
      borderTopWidth: 1,
      borderTopColor: tokens.readerDivider,
    },
    readingControlButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 8,
      paddingVertical: 6,
      borderRadius: density.radiusSm,
    },
    readingControlText: {
      fontSize: 14,
      lineHeight: 18,
      fontFamily: tokens.fontFamily,
      color: tokens.readerSecondaryText,
    },
    readingControlTextAccent: {
      color: tokens.accent,
      fontWeight: tokens.fontWeightSemibold,
    },
    readerSettingsLinkWrap: {
      paddingVertical: 14,
      paddingHorizontal: density.spacingLg,
      alignItems: 'center',
    },
    readerSettingsButton: {
      minHeight: 44,
      paddingHorizontal: 18,
      paddingVertical: 11,
      borderRadius: density.radiusPill,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderWidth: 1,
      borderColor: tokens.accent,
      backgroundColor: 'rgba(255,122,26,0.14)',
    },
    readerSettingsButtonText: {
      color: tokens.accent,
      fontFamily: tokens.fontFamily,
      fontSize: 15,
      lineHeight: 18,
      fontWeight: tokens.fontWeightSemibold,
    },

    compactHeaderCard: {
      width: '100%',
      borderRadius: density.radiusXl,
      marginHorizontal: 12,
      marginTop: 10,
      marginBottom: 8,
      paddingHorizontal: density.spacingLg,
      paddingVertical: density.spacingLg,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: tokens.readerCardBorder,
      backgroundColor: tokens.readerCardOpaque,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      ...cardShadow,
    },

    messagesContainer: {
      flex: 1,
    },
    list: {
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 20,
    },
    messageRow: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      marginBottom: 14,
      width: '100%',
    },
    avatarBox: {
      width: 34,
      height: 34,
      borderRadius: 11,
      marginRight: 10,
      overflow: 'hidden',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: tokens.messageOtherBorder,
      backgroundColor: tokens.avatarBg,
    },
    assistantAvatarIcon: {
      width: 28,
      height: 28,
    },
    messageBubble: {
      maxWidth: density.messageMaxWidth,
      paddingVertical: 11,
      paddingHorizontal: 14,
      borderRadius: 16,
      borderWidth: 1,
      overflow: 'hidden',
    },
    myBubble: {
      alignSelf: 'flex-end',
      borderBottomRightRadius: 6,
    },
    otherBubble: {
      alignSelf: 'flex-start',
      borderBottomLeftRadius: 6,
    },
    senderName: {
      fontSize: 10,
      lineHeight: 12,
      marginBottom: 4,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      fontFamily: tokens.fontFamily,
      fontWeight: tokens.fontWeightBold,
      color: tokens.accent,
    },
    messageText: {
      fontSize: 16,
      lineHeight: 22,
      color: tokens.messageText,
      fontFamily: tokens.fontFamily,
    },
    timeText: {
      fontSize: 10,
      lineHeight: 12,
      alignSelf: 'flex-end',
      marginTop: 6,
      color: tokens.messageMeta,
      fontFamily: tokens.fontFamily,
    },
    messageImage: {
      width: 236,
      height: 174,
      borderRadius: density.radiusSm,
      marginVertical: 4,
    },
    documentRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 8,
      paddingHorizontal: 2,
    },

    emptyState: {
      marginTop: 80,
      marginHorizontal: 24,
      borderRadius: density.radiusLg,
      borderWidth: 1,
      borderColor: tokens.emptyCardBorder,
      backgroundColor: tokens.emptyCard,
      paddingVertical: 28,
      paddingHorizontal: 20,
      alignItems: 'center',
    },
    emptyTitle: {
      fontSize: 19,
      lineHeight: 22,
      color: tokens.messageText,
      fontFamily: tokens.fontFamily,
      fontWeight: tokens.fontWeightSemibold,
    },
    emptySub: {
      marginTop: 8,
      fontSize: 15,
      lineHeight: 18,
      textAlign: 'center',
      color: tokens.messageMeta,
      fontFamily: tokens.fontFamily,
    },
    listenerModeBanner: {
      marginHorizontal: 12,
      marginTop: 8,
      marginBottom: 4,
      borderRadius: density.radiusMd,
      borderWidth: 1,
      borderColor: tokens.readerCardBorder,
      backgroundColor: tokens.readerCardOpaque,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    listenerModeBannerTitle: {
      color: tokens.readerPrimaryText,
      fontFamily: tokens.fontFamily,
      fontWeight: tokens.fontWeightSemibold,
      fontSize: 13,
      lineHeight: 16,
    },
    listenerModeBannerText: {
      marginTop: 3,
      color: tokens.readerSecondaryText,
      fontFamily: tokens.fontFamily,
      fontSize: 12,
      lineHeight: 16,
    },

    inputBarWrapper: {
      marginHorizontal: 12,
      marginTop: 6,
      marginBottom: 0,
      overflow: 'visible',
      borderRadius: density.radiusLg + 4,
      borderWidth: 1,
      borderColor: tokens.inputBarBorder,
      backgroundColor: tokens.inputBarOpaque,
      paddingHorizontal: 8,
      paddingVertical: 8,
      ...cardShadow,
    },
    inputBar: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 0,
      paddingVertical: 0,
      minHeight: density.inputBarMinHeight,
      backgroundColor: tokens.inputBar,
    },
    inputGradient: {
      ...StyleSheet.absoluteFillObject,
    },
    input: {
      flex: 1,
      minHeight: 44,
      maxHeight: 132,
      borderRadius: density.radiusLg + 2,
      paddingHorizontal: 16,
      paddingVertical: Platform.OS === 'ios' ? 12 : 10,
      fontSize: 17,
      lineHeight: 22,
      fontFamily: tokens.fontFamily,
      color: tokens.inputText,
      backgroundColor: tokens.inputField,
      borderWidth: 1,
      borderColor: tokens.inputFieldBorder,
    },
    sendButton: {
      width: density.inputSendButton,
      height: density.inputSendButton,
      borderRadius: density.inputSendButton / 2,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: tokens.accent,
      borderWidth: 1,
      borderColor: 'rgba(0,0,0,0.08)',
      ...subtleShadow,
    },
    supportOverlay: {
      flex: 1,
      backgroundColor: 'rgba(2,6,23,0.56)',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 20,
    },
    supportCard: {
      width: '100%',
      borderRadius: density.radiusLg,
      borderWidth: 1,
      borderColor: tokens.readerCardBorder,
      backgroundColor: tokens.readerCardOpaque,
      paddingHorizontal: 16,
      paddingVertical: 14,
      ...cardShadow,
    },
    supportBlink: {
      fontSize: 22,
      textAlign: 'center',
      marginBottom: 6,
    },
    supportTitle: {
      color: tokens.readerPrimaryText,
      fontSize: 20,
      lineHeight: 24,
      textAlign: 'center',
      fontFamily: tokens.fontFamily,
      fontWeight: tokens.fontWeightBold,
      marginBottom: 10,
    },
    supportBenefitText: {
      color: tokens.readerSecondaryText,
      fontSize: 14,
      lineHeight: 19,
      fontFamily: tokens.fontFamily,
      marginBottom: 4,
    },
    supportCheckRow: {
      marginTop: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    supportCheckLabel: {
      color: tokens.readerPrimaryText,
      fontSize: 15,
      lineHeight: 18,
      fontFamily: tokens.fontFamily,
      fontWeight: tokens.fontWeightSemibold,
      flexShrink: 1,
      marginRight: 10,
    },
    supportAmountRow: {
      marginTop: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    supportAmountButton: {
      minWidth: 52,
      minHeight: 34,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: tokens.inputFieldBorder,
      backgroundColor: tokens.inputField,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 8,
    },
    supportAmountButtonText: {
      color: tokens.inputText,
      fontFamily: tokens.fontFamily,
      fontWeight: tokens.fontWeightSemibold,
      fontSize: 14,
    },
    supportAmountInputWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: tokens.inputFieldBorder,
      backgroundColor: tokens.inputField,
      borderRadius: 10,
      minHeight: 36,
      paddingHorizontal: 10,
      minWidth: 126,
      justifyContent: 'center',
    },
    supportAmountInput: {
      minWidth: 52,
      textAlign: 'right',
      color: tokens.readerPrimaryText,
      fontFamily: tokens.fontFamily,
      fontWeight: tokens.fontWeightBold,
      fontSize: 16,
      paddingVertical: 0,
      paddingHorizontal: 0,
    },
    supportAmountSuffix: {
      marginLeft: 6,
      color: tokens.readerSecondaryText,
      fontFamily: tokens.fontFamily,
      fontWeight: tokens.fontWeightSemibold,
      fontSize: 13,
    },
    supportActions: {
      marginTop: 14,
      flexDirection: 'row',
      gap: 10,
    },
    supportLaterButton: {
      flex: 1,
      minHeight: 44,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: tokens.inputFieldBorder,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: tokens.inputField,
    },
    supportLaterButtonText: {
      color: tokens.inputText,
      fontFamily: tokens.fontFamily,
      fontWeight: tokens.fontWeightSemibold,
      fontSize: 14,
    },
    supportConfirmButton: {
      flex: 1,
      minHeight: 44,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: tokens.accent,
    },
    supportConfirmButtonText: {
      color: tokens.accentTextOnPrimary,
      fontFamily: tokens.fontFamily,
      fontWeight: tokens.fontWeightBold,
      fontSize: 14,
    },
  });
};
