package main

import (
	"log"
	"rag-agent-server/internal/database"
	"rag-agent-server/internal/models"
	"rag-agent-server/internal/services"
	"strings"

	"github.com/joho/godotenv"
	"golang.org/x/crypto/bcrypt"
)

func ensureUniqueInviteCode() string {
	for i := 0; i < 20; i++ {
		code := services.GenerateInviteCode()
		var existingCount int64
		if err := database.DB.Model(&models.User{}).Where("invite_code = ?", code).Count(&existingCount).Error; err == nil && existingCount == 0 {
			return code
		}
	}
	return services.GenerateInviteCode()
}

func main() {
	if err := godotenv.Load("../../.env"); err != nil {
		log.Println("No .env file found")
	}

	database.Connect()

	ragService := services.NewRAGService()

	testUsers := []models.User{
		{
			KarmicName:    "Alex Petrov",
			SpiritualName: "Arjuna Das",
			Email:         "arjuna@test.com",
			Password:      "password123",
			Gender:        "Male",
			Country:       "Russia",
			City:          "Moscow",
			Identity:      "Devotee",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Prabhupada",
			Dob:           "1990-01-01",
			Intentions:    "business,family",
			Skills:        "Management, Leadership",
			Industry:      "IT",
		},
		{
			KarmicName:    "Sita Devi",
			SpiritualName: "Sita Gopi",
			Email:         "sita@test.com",
			Password:      "password123",
			Gender:        "Female",
			Country:       "India",
			City:          "Vrindavan",
			Identity:      "Practitioner",
			Diet:          "Vegan",
			Madh:          "Gaudiya",
			Mentor:        "Guru",
			Dob:           "1995-05-10",
			Intentions:    "seva",
			Skills:        "Cooking, Kirtan",
		},
		{
			KarmicName:    "John Smith",
			SpiritualName: "Janaka Muni",
			Email:         "john@test.com",
			Password:      "password123",
			Gender:        "Male",
			Country:       "USA",
			City:          "Los Angeles",
			Identity:      "Student",
			Diet:          "Lacto-Vegetarian",
			Madh:          "Brahma",
			Mentor:        "Teacher",
			Dob:           "1985-11-20",
		},
		{
			KarmicName:    "Maria Garcia",
			SpiritualName: "Mirabai Devi",
			Email:         "mirabai@test.com",
			Password:      "password123",
			Gender:        "Female",
			Country:       "Spain",
			City:          "Madrid",
			Identity:      "Devotee",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Guru",
			Dob:           "1988-03-15",
		},
		{
			KarmicName:    "Yuki Tanaka",
			SpiritualName: "Yamuna Das",
			Email:         "yamuna@test.com",
			Password:      "password123",
			Gender:        "Male",
			Country:       "Japan",
			City:          "Tokyo",
			Identity:      "Practitioner",
			Diet:          "Vegan",
			Madh:          "Gaudiya",
			Mentor:        "Teacher",
			Dob:           "1992-08-22",
			Intentions:    "business,friendship",
			Skills:        "Go, React",
			Industry:      "IT",
		},
		{
			KarmicName:    "Anna Kowalski",
			SpiritualName: "Ananda Devi",
			Email:         "ananda@test.com",
			Password:      "password123",
			Gender:        "Female",
			Country:       "Poland",
			City:          "Krakow",
			Identity:      "Student",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Prabhupada",
			Dob:           "1996-12-05",
		},
		{
			KarmicName:    "Hans Mueller",
			SpiritualName: "Hari Das",
			Email:         "hari@test.com",
			Password:      "password123",
			Gender:        "Male",
			Country:       "Germany",
			City:          "Berlin",
			Identity:      "Devotee",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Guru",
			Dob:           "1987-07-18",
		},
		{
			KarmicName:    "Elena Rossi",
			SpiritualName: "Ekalavya Devi",
			Email:         "ekalavya@test.com",
			Password:      "password123",
			Gender:        "Female",
			Country:       "Italy",
			City:          "Rome",
			Identity:      "Practitioner",
			Diet:          "Vegan",
			Madh:          "Gaudiya",
			Mentor:        "Teacher",
			Dob:           "1993-04-30",
		},
		{
			KarmicName:    "James Wilson",
			SpiritualName: "Jaya Das",
			Email:         "jaya@test.com",
			Password:      "password123",
			Gender:        "Male",
			Country:       "Canada",
			City:          "Toronto",
			Identity:      "Student",
			Diet:          "Lacto-Vegetarian",
			Madh:          "Brahma",
			Mentor:        "Prabhupada",
			Dob:           "1991-09-12",
		},
		{
			KarmicName:    "Olga Ivanova",
			SpiritualName: "Radha Devi",
			Email:         "radha@test.com",
			Password:      "password123",
			Gender:        "Female",
			Country:       "Ukraine",
			City:          "Kyiv",
			Identity:      "Devotee",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Guru",
			Dob:           "1994-06-25",
		},
		{
			KarmicName:    "Pedro Silva",
			SpiritualName: "Partha Das",
			Email:         "partha@test.com",
			Password:      "password123",
			Gender:        "Male",
			Country:       "Brazil",
			City:          "Rio de Janeiro",
			Identity:      "Seeker",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Prabhupada",
			Dob:           "1998-02-14",
			Interests:     "Kirtan, Music",
		},
		{
			KarmicName:    "Sarah Jones",
			SpiritualName: "Satyabhama Devi",
			Email:         "satyabhama@test.com",
			Password:      "password123",
			Gender:        "Female",
			Country:       "Australia",
			City:          "Sydney",
			Identity:      "Devotee",
			Diet:          "Vegan",
			Madh:          "Gaudiya",
			Mentor:        "Guru",
			Dob:           "1990-11-30",
			Interests:     "Cooking, Deity Worship",
		},
		{
			KarmicName:    "Jean Dupont",
			SpiritualName: "Jagannath Das",
			Email:         "jagannath@test.com",
			Password:      "password123",
			Gender:        "Male",
			Country:       "France",
			City:          "Paris",
			Identity:      "Student",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Teacher",
			Dob:           "1985-05-20",
			Interests:     "Philosophy, Reading",
		},
		{
			KarmicName:    "Li Wei",
			SpiritualName: "Lila Devi",
			Email:         "lila@test.com",
			Password:      "password123",
			Gender:        "Female",
			Country:       "China",
			City:          "Beijing",
			Identity:      "Practitioner",
			Diet:          "Vegan",
			Madh:          "Brahma",
			Mentor:        "Prabhupada",
			Dob:           "1993-09-10",
			Interests:     "Yoga, Meditation",
		},
		{
			KarmicName:    "Amina Al-Fayed",
			SpiritualName: "Amrita Devi",
			Email:         "amrita@test.com",
			Password:      "password123",
			Gender:        "Female",
			Country:       "Egypt",
			City:          "Cairo",
			Identity:      "Seeker",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Guru",
			Dob:           "1997-04-05",
			Interests:     "Meditation, Service",
		},
		// Business Profiles
		{
			KarmicName:         "Ravi Gupta",
			SpiritualName:      "Ramananda Das",
			Email:              "ravi@test.com",
			Password:           "password123",
			Gender:             "Male",
			Country:            "India",
			City:               "Mumbai",
			Identity:           "Devotee",
			Diet:               "Vegetarian",
			Madh:               "Gaudiya",
			Mentor:             "Guru",
			Dob:                "1985-06-15",
			Intentions:         "business",
			Skills:             "Restaurant Management, Cooking",
			Industry:           "Hospitality",
			LookingForBusiness: "Partners for vegetarian cafe chain expansion",
		},
		{
			KarmicName:         "Svetlana Petrova",
			SpiritualName:      "Satyavati Devi",
			Email:              "svetlana@test.com",
			Password:           "password123",
			Gender:             "Female",
			Country:            "Russia",
			City:               "St. Petersburg",
			Identity:           "Practitioner",
			Diet:               "Vegan",
			Madh:               "Brahma",
			Mentor:             "Teacher",
			Dob:                "1990-03-22",
			Intentions:         "business,friendship",
			Skills:             "Yoga Instruction, Studio Management",
			Industry:           "Wellness",
			LookingForBusiness: "Yoga teachers and studio administrators",
		},
		{
			KarmicName:         "Vikram Singh",
			SpiritualName:      "Vamana Das",
			Email:              "vikram@test.com",
			Password:           "password123",
			Gender:             "Male",
			Country:            "USA",
			City:               "San Francisco",
			Identity:           "Devotee",
			Diet:               "Vegetarian",
			Madh:               "Gaudiya",
			Mentor:             "Prabhupada",
			Dob:                "1988-11-10",
			Intentions:         "business",
			Skills:             "Software Architecture, Cloud Computing",
			Industry:           "IT",
			LookingForBusiness: "Remote Go/React developers for dharmic projects",
		},
		{
			KarmicName:         "Elena Smirnova",
			SpiritualName:      "Ekayani Devi",
			Email:              "elena.design@test.com",
			Password:           "password123",
			Gender:             "Female",
			Country:            "Germany",
			City:               "Munich",
			Identity:           "Seeker",
			Diet:               "Vegetarian",
			Madh:               "Gaudiya",
			Mentor:             "Guru",
			Dob:                "1995-08-30",
			Intentions:         "business,friendship",
			Skills:             "Graphic Design, UI/UX, Branding",
			Industry:           "Design",
			LookingForBusiness: "Freelance projects in eco and spiritual niche",
		},
		{
			KarmicName:         "Rajesh Kumar",
			SpiritualName:      "Ram Das",
			Email:              "rajesh@test.com",
			Password:           "password123",
			Gender:             "Male",
			Country:            "India",
			City:               "Bangalore",
			Identity:           "Devotee",
			Diet:               "Vegetarian",
			Madh:               "Sri",
			Mentor:             "Guru",
			Dob:                "1982-01-20",
			Intentions:         "business",
			Skills:             "Organic Farming, Supply Chain",
			Industry:           "Agriculture",
			LookingForBusiness: "Buyers for organic produce",
		},
		// Service & Friendship Profiles
		{
			KarmicName:         "Gopal Das",
			SpiritualName:      "Gopal Krishna Das",
			Email:              "gopal@test.com",
			Password:           "password123",
			Gender:             "Male",
			Country:            "UK",
			City:               "London",
			Identity:           "Devotee",
			Diet:               "Vegetarian",
			Madh:               "Gaudiya",
			Mentor:             "Prabhupada",
			Dob:                "1993-05-05",
			Intentions:         "seva",
			Skills:             "Event Management, Fundraising",
			Industry:           "Non-Profit",
			LookingForBusiness: "Volunteers for Rathayatra",
		},
		{
			KarmicName:         "Priya Patel",
			SpiritualName:      "Prema Bhakti Devi",
			Email:              "priya@test.com",
			Password:           "password123",
			Gender:             "Female",
			Country:            "USA",
			City:               "New York",
			Identity:           "Practitioner",
			Diet:               "Vegan",
			Madh:               "Gaudiya",
			Mentor:             "Guru",
			Dob:                "1996-09-12",
			Intentions:         "friendship,seva",
			Skills:             "Kirtan, Harmonium, Singing",
			Industry:           "Music",
			LookingForBusiness: "Kirtan group members",
		},
		{
			KarmicName:         "Ivan Popov",
			SpiritualName:      "Ishvara Das",
			Email:              "ivan@test.com",
			Password:           "password123",
			Gender:             "Male",
			Country:            "Russia",
			City:               "Sochi",
			Identity:           "Seeker",
			Diet:               "Vegetarian",
			Madh:               "Gaudiya",
			Mentor:             "Teacher",
			Dob:                "1998-02-28",
			Intentions:         "seva",
			Skills:             "Construction, Driving",
			Industry:           "General",
			LookingForBusiness: "Service opportunities in ashrams",
		},
		{
			KarmicName:         "Lakshmi Devi",
			SpiritualName:      "Lakshmi Priya Devi",
			Email:              "lakshmi@test.com",
			Password:           "password123",
			Gender:             "Female",
			Country:            "India",
			City:               "Delhi",
			Identity:           "Devotee",
			Diet:               "Vegetarian",
			Madh:               "Sri",
			Mentor:             "Guru",
			Dob:                "1980-12-15",
			Intentions:         "business,friendship",
			Skills:             "Ayurveda, Pulse Diagnosis",
			Industry:           "Healthcare",
			LookingForBusiness: "Patients and students",
		},
		{
			KarmicName:         "Michael Brown",
			SpiritualName:      "Madhava Das",
			Email:              "michael@test.com",
			Password:           "password123",
			Gender:             "Male",
			Country:            "Australia",
			City:               "Melbourne",
			Identity:           "Student",
			Diet:               "Vegetarian",
			Madh:               "Gaudiya",
			Mentor:             "Prabhupada",
			Dob:                "1994-07-07",
			Intentions:         "friendship",
			Skills:             "Teaching, Writing",
			Industry:           "Education",
			LookingForBusiness: "Study partners for Bhakti Sastri",
		},
	}

	testUsers = append(testUsers,
		models.User{
			KarmicName:         "Nikolai Sokolov",
			SpiritualName:      "Nitai Chandra Das",
			Email:              "nitai.family@test.com",
			Password:           "password123",
			Gender:             "Male",
			Country:            "Belarus",
			City:               "Minsk",
			Identity:           "Devotee",
			Diet:               "Vegetarian",
			Madh:               "Gaudiya",
			YogaStyle:          "Bhakti",
			Guna:               "Sattva",
			Mentor:             "Guru",
			Dob:                "1991-10-10",
			Bio:                "Temple volunteer and youth mentor looking for a dharmic family life.",
			Interests:          "Bhagavatam study, mentoring, kirtan",
			LookingFor:         "Marriage with shared spiritual practice",
			Intentions:         "family",
			Skills:             "Teaching, Community work",
			Industry:           "Education",
			MaritalStatus:      "Single",
			BirthTime:          "06:45",
			BirthPlaceLink:     "Minsk, Belarus",
			LookingForBusiness: "No active business search",
		},
		models.User{
			KarmicName:         "Devika Sharma",
			SpiritualName:      "Devaki Rani Devi",
			Email:              "devaki.family@test.com",
			Password:           "password123",
			Gender:             "Female",
			Country:            "India",
			City:               "Vrindavan",
			Identity:           "Practitioner",
			Diet:               "Vegan",
			Madh:               "Gaudiya",
			YogaStyle:          "Bhakti",
			Guna:               "Sattva",
			Mentor:             "Mataji Teacher",
			Dob:                "1994-02-17",
			Bio:                "Lives in dham and values simple living, sadhana and service.",
			Interests:          "Japa, deity seva, ayurvedic cooking",
			LookingFor:         "Conscious marriage and family",
			Intentions:         "family,seva",
			Skills:             "Cooking, Event volunteering",
			Industry:           "Wellness",
			MaritalStatus:      "Single",
			BirthTime:          "04:20",
			BirthPlaceLink:     "Mathura, India",
			LookingForBusiness: "Open to seva projects only",
		},
		models.User{
			KarmicName:         "Karina Sadykova",
			SpiritualName:      "Karuna Devi Dasi",
			Email:              "karuna.friend@test.com",
			Password:           "password123",
			Gender:             "Female",
			Country:            "Kazakhstan",
			City:               "Almaty",
			Identity:           "Seeker",
			Diet:               "Vegetarian",
			Madh:               "Gaudiya",
			YogaStyle:          "Hatha",
			Guna:               "Rajas",
			Mentor:             "Teacher",
			Dob:                "1999-09-01",
			Bio:                "Wants a spiritual social circle and collaborative service friends.",
			Interests:          "Pilgrimage, dancing, meditation",
			LookingFor:         "Friends for satsang and travel",
			Intentions:         "friendship",
			Skills:             "Event coordination, social media",
			Industry:           "Marketing",
			MaritalStatus:      "Single",
			BirthTime:          "13:10",
			BirthPlaceLink:     "Almaty, Kazakhstan",
			LookingForBusiness: "SMM collaborations in spiritual communities",
		},
		models.User{
			KarmicName:         "Suresh Adhikari",
			SpiritualName:      "Govinda Seva Das",
			Email:              "govinda.seva@test.com",
			Password:           "password123",
			Gender:             "Male",
			Country:            "Nepal",
			City:               "Kathmandu",
			Identity:           "Devotee",
			Diet:               "Vegetarian",
			Madh:               "Gaudiya",
			YogaStyle:          "Karma",
			Guna:               "Sattva",
			Mentor:             "Guru Maharaj",
			Dob:                "1989-12-03",
			Bio:                "Focused on practical seva and outreach in mountain regions.",
			Interests:          "Book distribution, hiking, kirtan",
			LookingFor:         "Seva teams and project partners",
			Intentions:         "seva,friendship",
			Skills:             "Logistics, driving, fundraising",
			Industry:           "Non-Profit",
			MaritalStatus:      "Single",
			BirthTime:          "09:55",
			BirthPlaceLink:     "Kathmandu, Nepal",
			LookingForBusiness: "Supporters for outreach yatra bus",
		},
		models.User{
			KarmicName:         "Farid Al Mansoor",
			SpiritualName:      "Veda Vishvakarma Das",
			Email:              "veda.biz@test.com",
			Password:           "password123",
			Gender:             "Male",
			Country:            "UAE",
			City:               "Dubai",
			Identity:           "Practitioner",
			Diet:               "Vegan",
			Madh:               "Sri",
			YogaStyle:          "Jnana",
			Guna:               "Rajas",
			Mentor:             "Teacher",
			Dob:                "1986-05-28",
			Bio:                "Building ethical tech ventures aligned with dharmic values.",
			Interests:          "Investing, Vedanta, product building",
			LookingFor:         "Business allies in mission-driven startups",
			Intentions:         "business",
			Skills:             "Product strategy, FinTech, hiring",
			Industry:           "Finance",
			MaritalStatus:      "Divorced",
			BirthTime:          "11:35",
			BirthPlaceLink:     "Dubai, UAE",
			LookingForBusiness: "Co-founders for faith-friendly finance app",
		},
		models.User{
			KarmicName:         "Thomas Green",
			SpiritualName:      "Tamal Krishna Das",
			Email:              "tamal.mix@test.com",
			Password:           "password123",
			Gender:             "Male",
			Country:            "USA",
			City:               "Austin",
			Identity:           "Student",
			Diet:               "Lacto-Vegetarian",
			Madh:               "Gaudiya",
			YogaStyle:          "Bhakti",
			Guna:               "Sattva",
			Mentor:             "Senior devotee",
			Dob:                "1995-07-14",
			Bio:                "Tech lead balancing startup life with steady sadhana.",
			Interests:          "Music production, coding, kirtan",
			LookingFor:         "Family and friendship in a spiritual ecosystem",
			Intentions:         "family,friendship,business",
			Skills:             "Go, React Native, team leadership",
			Industry:           "IT",
			MaritalStatus:      "Single",
			BirthTime:          "18:25",
			BirthPlaceLink:     "Austin, USA",
			LookingForBusiness: "Product and mobile engineers for spiritual apps",
		},
		models.User{
			KarmicName:         "Emily Carter",
			SpiritualName:      "Tulasi Prema Devi",
			Email:              "tulasi.mix@test.com",
			Password:           "password123",
			Gender:             "Female",
			Country:            "UK",
			City:               "Leeds",
			Identity:           "Devotee",
			Diet:               "Vegetarian",
			Madh:               "Gaudiya",
			YogaStyle:          "Bhakti",
			Guna:               "Sattva",
			Mentor:             "Mataji Mentor",
			Dob:                "1992-03-03",
			Bio:                "Kirtan teacher and counselor, values sincerity and consistency.",
			Interests:          "Counseling, kirtan, pilgrimage",
			LookingFor:         "Marriage and shared seva culture",
			Intentions:         "family,seva",
			Skills:             "Counseling, Kirtan, Group facilitation",
			Industry:           "Mental Health",
			MaritalStatus:      "Single",
			BirthTime:          "07:40",
			BirthPlaceLink:     "Leeds, UK",
			LookingForBusiness: "Collaboration for youth retreats",
		},
		models.User{
			KarmicName:         "Natalia Belova",
			SpiritualName:      "Sundari Devi",
			Email:              "sundari.mature@test.com",
			Password:           "password123",
			Gender:             "Female",
			Country:            "Latvia",
			City:               "Riga",
			Identity:           "Devotee",
			Diet:               "Vegetarian",
			Madh:               "Gaudiya",
			YogaStyle:          "Bhakti",
			Guna:               "Sattva",
			Mentor:             "Guru",
			Dob:                "1978-11-11",
			Bio:                "Experienced mentor open to a respectful mature relationship.",
			Interests:          "Japa walks, scriptures, handicrafts",
			LookingFor:         "Stable family-oriented partnership",
			Intentions:         "family,friendship",
			Skills:             "Mentorship, handicrafts",
			Industry:           "Art",
			MaritalStatus:      "Widowed",
			BirthTime:          "05:30",
			BirthPlaceLink:     "Riga, Latvia",
			LookingForBusiness: "Handmade spiritual goods collaboration",
		},
		models.User{
			KarmicName:         "Ilya Morozov",
			SpiritualName:      "Bhakta Ishan Das",
			Email:              "bhakta.young@test.com",
			Password:           "password123",
			Gender:             "Male",
			Country:            "Georgia",
			City:               "Tbilisi",
			Identity:           "Seeker",
			Diet:               "Vegetarian",
			Madh:               "Gaudiya",
			YogaStyle:          "Kirtan",
			Guna:               "Rajas",
			Mentor:             "Bhakta leader",
			Dob:                "2003-04-19",
			Bio:                "Early-career devotee seeking community and seva opportunities.",
			Interests:          "Media seva, editing, festivals",
			LookingFor:         "Friends and seva team",
			Intentions:         "friendship,seva",
			Skills:             "Video editing, social media",
			Industry:           "Media",
			MaritalStatus:      "Single",
			BirthTime:          "15:05",
			BirthPlaceLink:     "Tbilisi, Georgia",
			LookingForBusiness: "Creative team for kirtan content",
		},
		models.User{
			KarmicName:         "Andrei Volk",
			SpiritualName:      "Aniruddha Das",
			Email:              "aniruddha.health@test.com",
			Password:           "password123",
			Gender:             "Male",
			Country:            "Czech Republic",
			City:               "Prague",
			Identity:           "Practitioner",
			Diet:               "Vegan",
			Madh:               "Sri",
			YogaStyle:          "Raja",
			Guna:               "Sattva",
			Mentor:             "Teacher",
			Dob:                "1984-01-08",
			Bio:                "Doctor and yoga therapist building preventive healthcare services.",
			Interests:          "Ayurveda, pranayama, community health",
			LookingFor:         "Business and seva collaborations",
			Intentions:         "business,seva",
			Skills:             "Medicine, Ayurveda, coaching",
			Industry:           "Healthcare",
			MaritalStatus:      "Divorced",
			BirthTime:          "10:12",
			BirthPlaceLink:     "Prague, Czech Republic",
			LookingForBusiness: "Partners for online ayurveda clinic",
		},
	)

	for _, u := range testUsers {
		if strings.TrimSpace(u.Intentions) == "" {
			u.Intentions = "friendship"
		}

		if strings.TrimSpace(u.LookingFor) == "" {
			switch {
			case strings.Contains(u.Intentions, "family"):
				u.LookingFor = "Conscious marriage and family life"
			case strings.Contains(u.Intentions, "business"):
				u.LookingFor = "Business partnerships in aligned values"
			case strings.Contains(u.Intentions, "seva"):
				u.LookingFor = "Service team and volunteer projects"
			default:
				u.LookingFor = "Meaningful spiritual friendships"
			}
		}

		hashed, _ := bcrypt.GenerateFromPassword([]byte(u.Password), bcrypt.DefaultCost)
		u.Password = string(hashed)
		u.IsProfileComplete = true
		u.DatingEnabled = true // Enable dating for test users
		if u.InviteCode == "" {
			u.InviteCode = ensureUniqueInviteCode()
		}

		var existing models.User
		if err := database.DB.Where("email = ?", u.Email).First(&existing).Error; err == nil {
			log.Printf("User %s exists, updating dating status and networking fields...", u.Email)
			updateFields := map[string]interface{}{
				"karmic_name":          u.KarmicName,
				"spiritual_name":       u.SpiritualName,
				"password":             u.Password,
				"gender":               u.Gender,
				"country":              u.Country,
				"city":                 u.City,
				"identity":             u.Identity,
				"diet":                 u.Diet,
				"madh":                 u.Madh,
				"yoga_style":           u.YogaStyle,
				"guna":                 u.Guna,
				"mentor":               u.Mentor,
				"dob":                  u.Dob,
				"bio":                  u.Bio,
				"interests":            u.Interests,
				"looking_for":          u.LookingFor,
				"intentions":           u.Intentions,
				"skills":               u.Skills,
				"industry":             u.Industry,
				"looking_for_business": u.LookingForBusiness,
				"marital_status":       u.MaritalStatus,
				"birth_time":           u.BirthTime,
				"birth_place_link":     u.BirthPlaceLink,
				"dating_enabled":       true,
				"is_profile_complete":  true,
			}
			if existing.InviteCode == "" {
				updateFields["invite_code"] = ensureUniqueInviteCode()
			}
			if err := database.DB.Model(&existing).Updates(updateFields).Error; err != nil {
				log.Printf("Failed to update user %s: %v", u.Email, err)
			}
			continue
		}

		if err := database.DB.Create(&u).Error; err != nil {
			log.Printf("Failed to create user %s: %v", u.Email, err)
			continue
		}

		log.Printf("Created user: %s (%s, %s). Uploading to RAG...", u.Email, u.Country, u.City)
		fileID, err := ragService.UploadProfile(u)
		if err != nil {
			log.Printf("RAG Error for %s: %v", u.Email, err)
		} else {
			u.RagFileID = fileID
			database.DB.Model(&u).Update("rag_file_id", fileID)
			log.Printf("RAG Success for %s: %s", u.Email, fileID)
		}
	}

	log.Println("Seeding completed!")
}
