package main

import (
	"log"
	"rag-agent-server/internal/database"
	"rag-agent-server/internal/models"
	"rag-agent-server/internal/services"

	"github.com/joho/godotenv"
	"golang.org/x/crypto/bcrypt"
)

func main() {
	if err := godotenv.Load("../../.env"); err != nil {
		log.Println("No .env file found")
	}

	database.Connect()

	ragService := services.NewRAGService()

	testUsers := []models.User{
		{
			KarmicName:    "Alex Petrov",
			SpiritualName: "Arjuna Das",
			Email:         "arjuna@test.com",
			Password:      "password123",
			Gender:        "Male",
			Country:       "Russia",
			City:          "Moscow",
			Identity:      "Devotee",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Prabhupada",
			Dob:           "1990-01-01",
			Intentions:    "business,family",
			Skills:        "Management, Leadership",
			Industry:      "IT",
		},
		{
			KarmicName:    "Sita Devi",
			SpiritualName: "Sita Gopi",
			Email:         "sita@test.com",
			Password:      "password123",
			Gender:        "Female",
			Country:       "India",
			City:          "Vrindavan",
			Identity:      "Practitioner",
			Diet:          "Vegan",
			Madh:          "Gaudiya",
			Mentor:        "Guru",
			Dob:           "1995-05-10",
			Intentions:    "seva",
			Skills:        "Cooking, Kirtan",
		},
		{
			KarmicName:    "John Smith",
			SpiritualName: "Janaka Muni",
			Email:         "john@test.com",
			Password:      "password123",
			Gender:        "Male",
			Country:       "USA",
			City:          "Los Angeles",
			Identity:      "Student",
			Diet:          "Lacto-Vegetarian",
			Madh:          "Brahma",
			Mentor:        "Teacher",
			Dob:           "1985-11-20",
		},
		{
			KarmicName:    "Maria Garcia",
			SpiritualName: "Mirabai Devi",
			Email:         "mirabai@test.com",
			Password:      "password123",
			Gender:        "Female",
			Country:       "Spain",
			City:          "Madrid",
			Identity:      "Devotee",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Guru",
			Dob:           "1988-03-15",
		},
		{
			KarmicName:    "Yuki Tanaka",
			SpiritualName: "Yamuna Das",
			Email:         "yamuna@test.com",
			Password:      "password123",
			Gender:        "Male",
			Country:       "Japan",
			City:          "Tokyo",
			Identity:      "Practitioner",
			Diet:          "Vegan",
			Madh:          "Gaudiya",
			Mentor:        "Teacher",
			Dob:           "1992-08-22",
			Intentions:    "business,friendship",
			Skills:        "Go, React",
			Industry:      "IT",
		},
		{
			KarmicName:    "Anna Kowalski",
			SpiritualName: "Ananda Devi",
			Email:         "ananda@test.com",
			Password:      "password123",
			Gender:        "Female",
			Country:       "Poland",
			City:          "Krakow",
			Identity:      "Student",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Prabhupada",
			Dob:           "1996-12-05",
		},
		{
			KarmicName:    "Hans Mueller",
			SpiritualName: "Hari Das",
			Email:         "hari@test.com",
			Password:      "password123",
			Gender:        "Male",
			Country:       "Germany",
			City:          "Berlin",
			Identity:      "Devotee",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Guru",
			Dob:           "1987-07-18",
		},
		{
			KarmicName:    "Elena Rossi",
			SpiritualName: "Ekalavya Devi",
			Email:         "ekalavya@test.com",
			Password:      "password123",
			Gender:        "Female",
			Country:       "Italy",
			City:          "Rome",
			Identity:      "Practitioner",
			Diet:          "Vegan",
			Madh:          "Gaudiya",
			Mentor:        "Teacher",
			Dob:           "1993-04-30",
		},
		{
			KarmicName:    "James Wilson",
			SpiritualName: "Jaya Das",
			Email:         "jaya@test.com",
			Password:      "password123",
			Gender:        "Male",
			Country:       "Canada",
			City:          "Toronto",
			Identity:      "Student",
			Diet:          "Lacto-Vegetarian",
			Madh:          "Brahma",
			Mentor:        "Prabhupada",
			Dob:           "1991-09-12",
		},
		{
			KarmicName:    "Olga Ivanova",
			SpiritualName: "Radha Devi",
			Email:         "radha@test.com",
			Password:      "password123",
			Gender:        "Female",
			Country:       "Ukraine",
			City:          "Kyiv",
			Identity:      "Devotee",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Guru",
			Dob:           "1994-06-25",
		},
		{
			KarmicName:    "Pedro Silva",
			SpiritualName: "Partha Das",
			Email:         "partha@test.com",
			Password:      "password123",
			Gender:        "Male",
			Country:       "Brazil",
			City:          "Rio de Janeiro",
			Identity:      "Seeker",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Prabhupada",
			Dob:           "1998-02-14",
			Interests:     "Kirtan, Music",
		},
		{
			KarmicName:    "Sarah Jones",
			SpiritualName: "Satyabhama Devi",
			Email:         "satyabhama@test.com",
			Password:      "password123",
			Gender:        "Female",
			Country:       "Australia",
			City:          "Sydney",
			Identity:      "Devotee",
			Diet:          "Vegan",
			Madh:          "Gaudiya",
			Mentor:        "Guru",
			Dob:           "1990-11-30",
			Interests:     "Cooking, Deity Worship",
		},
		{
			KarmicName:    "Jean Dupont",
			SpiritualName: "Jagannath Das",
			Email:         "jagannath@test.com",
			Password:      "password123",
			Gender:        "Male",
			Country:       "France",
			City:          "Paris",
			Identity:      "Student",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Teacher",
			Dob:           "1985-05-20",
			Interests:     "Philosophy, Reading",
		},
		{
			KarmicName:    "Li Wei",
			SpiritualName: "Lila Devi",
			Email:         "lila@test.com",
			Password:      "password123",
			Gender:        "Female",
			Country:       "China",
			City:          "Beijing",
			Identity:      "Practitioner",
			Diet:          "Vegan",
			Madh:          "Brahma",
			Mentor:        "Prabhupada",
			Dob:           "1993-09-10",
			Interests:     "Yoga, Meditation",
		},
		{
			KarmicName:    "Amina Al-Fayed",
			SpiritualName: "Amrita Devi",
			Email:         "amrita@test.com",
			Password:      "password123",
			Gender:        "Female",
			Country:       "Egypt",
			City:          "Cairo",
			Identity:      "Seeker",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Guru",
			Dob:           "1997-04-05",
			Interests:     "Meditation, Service",
		},
		// Business Profiles
		{
			KarmicName:    "Ravi Gupta",
			SpiritualName: "Ramananda Das",
			Email:         "ravi@test.com",
			Password:      "password123",
			Gender:        "Male",
			Country:       "India",
			City:          "Mumbai",
			Identity:      "Devotee",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Guru",
			Dob:           "1985-06-15",
			Intentions:    "business",
			Skills:        "Restaurant Management, Cooking",
			Industry:      "Hospitality",
			LookingForBusiness: "Partners for vegetarian cafe chain expansion",
		},
		{
			KarmicName:    "Svetlana Petrova",
			SpiritualName: "Satyavati Devi",
			Email:         "svetlana@test.com",
			Password:      "password123",
			Gender:        "Female",
			Country:       "Russia",
			City:          "St. Petersburg",
			Identity:      "Practitioner",
			Diet:          "Vegan",
			Madh:          "Brahma",
			Mentor:        "Teacher",
			Dob:           "1990-03-22",
			Intentions:    "business,friendship",
			Skills:        "Yoga Instruction, Studio Management",
			Industry:      "Wellness",
			LookingForBusiness: "Yoga teachers and studio administrators",
		},
		{
			KarmicName:    "Vikram Singh",
			SpiritualName: "Vamana Das",
			Email:         "vikram@test.com",
			Password:      "password123",
			Gender:        "Male",
			Country:       "USA",
			City:          "San Francisco",
			Identity:      "Devotee",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Prabhupada",
			Dob:           "1988-11-10",
			Intentions:    "business",
			Skills:        "Software Architecture, Cloud Computing",
			Industry:      "IT",
			LookingForBusiness: "Remote Go/React developers for dharmic projects",
		},
		{
			KarmicName:    "Elena Smirnova",
			SpiritualName: "Ekayani Devi",
			Email:         "elena.design@test.com",
			Password:      "password123",
			Gender:        "Female",
			Country:       "Germany",
			City:          "Munich",
			Identity:      "Seeker",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Guru",
			Dob:           "1995-08-30",
			Intentions:    "business,friendship",
			Skills:        "Graphic Design, UI/UX, Branding",
			Industry:      "Design",
			LookingForBusiness: "Freelance projects in eco and spiritual niche",
		},
		{
			KarmicName:    "Rajesh Kumar",
			SpiritualName: "Ram Das",
			Email:         "rajesh@test.com",
			Password:      "password123",
			Gender:        "Male",
			Country:       "India",
			City:          "Bangalore",
			Identity:      "Devotee",
			Diet:          "Vegetarian",
			Madh:          "Sri",
			Mentor:        "Guru",
			Dob:           "1982-01-20",
			Intentions:    "business",
			Skills:        "Organic Farming, Supply Chain",
			Industry:      "Agriculture",
			LookingForBusiness: "Buyers for organic produce",
		},
		// Service & Friendship Profiles
		{
			KarmicName:    "Gopal Das",
			SpiritualName: "Gopal Krishna Das",
			Email:         "gopal@test.com",
			Password:      "password123",
			Gender:        "Male",
			Country:       "UK",
			City:          "London",
			Identity:      "Devotee",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Prabhupada",
			Dob:           "1993-05-05",
			Intentions:    "seva",
			Skills:        "Event Management, Fundraising",
			Industry:      "Non-Profit",
			LookingForBusiness: "Volunteers for Rathayatra",
		},
		{
			KarmicName:    "Priya Patel",
			SpiritualName: "Prema Bhakti Devi",
			Email:         "priya@test.com",
			Password:      "password123",
			Gender:        "Female",
			Country:       "USA",
			City:          "New York",
			Identity:      "Practitioner",
			Diet:          "Vegan",
			Madh:          "Gaudiya",
			Mentor:        "Guru",
			Dob:           "1996-09-12",
			Intentions:    "friendship,seva",
			Skills:        "Kirtan, Harmonium, Singing",
			Industry:      "Music",
			LookingForBusiness: "Kirtan group members",
		},
		{
			KarmicName:    "Ivan Popov",
			SpiritualName: "Ishvara Das",
			Email:         "ivan@test.com",
			Password:      "password123",
			Gender:        "Male",
			Country:       "Russia",
			City:          "Sochi",
			Identity:      "Seeker",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Teacher",
			Dob:           "1998-02-28",
			Intentions:    "seva",
			Skills:        "Construction, Driving",
			Industry:      "General",
			LookingForBusiness: "Service opportunities in ashrams",
		},
		{
			KarmicName:    "Lakshmi Devi",
			SpiritualName: "Lakshmi Priya Devi",
			Email:         "lakshmi@test.com",
			Password:      "password123",
			Gender:        "Female",
			Country:       "India",
			City:          "Delhi",
			Identity:      "Devotee",
			Diet:          "Vegetarian",
			Madh:          "Sri",
			Mentor:        "Guru",
			Dob:           "1980-12-15",
			Intentions:    "business,friendship",
			Skills:        "Ayurveda, Pulse Diagnosis",
			Industry:      "Healthcare",
			LookingForBusiness: "Patients and students",
		},
		{
			KarmicName:    "Michael Brown",
			SpiritualName: "Madhava Das",
			Email:         "michael@test.com",
			Password:      "password123",
			Gender:        "Male",
			Country:       "Australia",
			City:          "Melbourne",
			Identity:      "Student",
			Diet:          "Vegetarian",
			Madh:          "Gaudiya",
			Mentor:        "Prabhupada",
			Dob:           "1994-07-07",
			Intentions:    "friendship",
			Skills:        "Teaching, Writing",
			Industry:      "Education",
			LookingForBusiness: "Study partners for Bhakti Sastri",
		},
	}

	for _, u := range testUsers {
		hashed, _ := bcrypt.GenerateFromPassword([]byte(u.Password), bcrypt.DefaultCost)
		u.Password = string(hashed)
		u.IsProfileComplete = true
		u.DatingEnabled = true // Enable dating for test users

		var existing models.User
		if err := database.DB.Where("email = ?", u.Email).First(&existing).Error; err == nil {
			log.Printf("User %s exists, updating dating status and networking fields...", u.Email)
			database.DB.Model(&existing).Updates(map[string]interface{}{
				"dating_enabled": true,
				"intentions":     u.Intentions,
				"skills":         u.Skills,
				"industry":       u.Industry,
			})
			continue
		}

		if err := database.DB.Create(&u).Error; err != nil {
			log.Printf("Failed to create user %s: %v", u.Email, err)
			continue
		}

		log.Printf("Created user: %s (%s, %s). Uploading to RAG...", u.Email, u.Country, u.City)
		fileID, err := ragService.UploadProfile(u)
		if err != nil {
			log.Printf("RAG Error for %s: %v", u.Email, err)
		} else {
			u.RagFileID = fileID
			database.DB.Model(&u).Update("rag_file_id", fileID)
			log.Printf("RAG Success for %s: %s", u.Email, fileID)
		}
	}

	log.Println("Seeding completed!")
}